#!/usr/bin/env bash
# =============================================================================
# generate-container-docs.sh - Generate CONTAINER_TOOLS.md from CI artifacts
# =============================================================================
#
# Combines Syft SBOM, Trivy scan results, and runtime inventory output into
# a single CONTAINER_TOOLS.md document.
#
# Usage:
#   bash scripts/generate-container-docs.sh <sbom.json> <trivy.json> <runtime.md>
#
# Dependencies: jq (available on ubuntu-latest CI runners)
#
# =============================================================================

set -euo pipefail

SBOM_JSON="${1:?Usage: $0 <sbom.json> <trivy.json> <runtime.md>}"
TRIVY_JSON="${2:?Usage: $0 <sbom.json> <trivy.json> <runtime.md>}"
RUNTIME_MD="${3:?Usage: $0 <sbom.json> <trivy.json> <runtime.md>}"

# Validate inputs
for f in "$SBOM_JSON" "$TRIVY_JSON" "$RUNTIME_MD"; do
    if [ ! -f "$f" ]; then
        echo "ERROR: File not found: $f" >&2
        exit 1
    fi
done

if ! command -v jq >/dev/null 2>&1; then
    echo "ERROR: jq is required but not installed" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Extract metadata from Syft SBOM
# ---------------------------------------------------------------------------

DISTRO_NAME=$(jq -r '.distro.prettyName // "Unknown"' "$SBOM_JSON")
DISTRO_ID=$(jq -r '.distro.id // "Unknown"' "$SBOM_JSON")
DISTRO_VERSION=$(jq -r '.distro.versionID // "Unknown"' "$SBOM_JSON")

DEB_COUNT=$(jq '[.artifacts[] | select(.type == "deb-pkg")] | length' "$SBOM_JSON")
NPM_COUNT=$(jq '[.artifacts[] | select(.type == "npm-pkg")] | length' "$SBOM_JSON")
GO_COUNT=$(jq '[.artifacts[] | select(.type == "go-module-pkg")] | length' "$SBOM_JSON")
BINARY_COUNT=$(jq '[.artifacts[] | select(.type == "binary-pkg")] | length' "$SBOM_JSON")
TOTAL_ARTIFACTS=$(jq '.artifacts | length' "$SBOM_JSON")

# ---------------------------------------------------------------------------
# Extract vulnerability data from Trivy
# ---------------------------------------------------------------------------

VULN_CRITICAL=$(jq '[.Results[]?.Vulnerabilities[]? | select(.Severity == "CRITICAL")] | length' "$TRIVY_JSON")
VULN_HIGH=$(jq '[.Results[]?.Vulnerabilities[]? | select(.Severity == "HIGH")] | length' "$TRIVY_JSON")
VULN_MEDIUM=$(jq '[.Results[]?.Vulnerabilities[]? | select(.Severity == "MEDIUM")] | length' "$TRIVY_JSON")
VULN_LOW=$(jq '[.Results[]?.Vulnerabilities[]? | select(.Severity == "LOW")] | length' "$TRIVY_JSON")
VULN_TOTAL=$((VULN_CRITICAL + VULN_HIGH + VULN_MEDIUM + VULN_LOW))

# ---------------------------------------------------------------------------
# Generate document
# ---------------------------------------------------------------------------

GENERATION_DATE=$(date -u +%Y-%m-%d)

cat <<HEADER
# OpenClaw Container Tools and Environment

**Image**: \`ghcr.io/jedwards1230/openclaw:latest\`
**Base**: \`node:22-bookworm\` ($DISTRO_NAME)
**Deployment**: Kubernetes (namespace: \`home-agent\`)

> Auto-generated by CI on $GENERATION_DATE using Syft (SBOM), Trivy (CVEs), and runtime probing.
> Do not edit manually — changes will be overwritten on next image build.

## Table of Contents

- [Operating System](#operating-system)
- [Installed Packages Summary](#installed-packages-summary)
- [Language Runtimes](#language-runtimes)
- [Package Managers](#package-managers)
- [CLI Tools](#cli-tools)
- [Vulnerability Summary](#vulnerability-summary)
- [Runtime Environment](#runtime-environment)

---

HEADER

# ===== Operating System =====
cat <<EOF
## Operating System

| Component | Value |
|-----------|-------|
| Distribution | $DISTRO_NAME |
| Version ID | $DISTRO_VERSION |
| Distribution ID | $DISTRO_ID |
| Total Artifacts | $TOTAL_ARTIFACTS (Syft-detected) |

EOF

# ===== Installed Packages Summary =====
cat <<EOF
## Installed Packages Summary

| Package Type | Count |
|-------------|-------|
| Debian packages (deb) | $DEB_COUNT |
| npm packages | $NPM_COUNT |
| Go modules | $GO_COUNT |
| Binary packages | $BINARY_COUNT |
| **Total** | **$TOTAL_ARTIFACTS** |

EOF

# ===== Language Runtimes =====
echo "## Language Runtimes"
echo ""
echo "Detected by Syft as binary or package artifacts:"
echo ""
echo "| Runtime | Version | Source |"
echo "|---------|---------|--------|"

# Node.js
NODE_VER=$(jq -r '[.artifacts[] | select(.name == "node" and .type == "binary-pkg")] | first | .version // "Not found"' "$SBOM_JSON")
echo "| Node.js | $NODE_VER | binary |"

# Python
PYTHON_VER=$(jq -r '[.artifacts[] | select(.name == "python3" or .name == "python3.11") | select(.type == "deb-pkg")] | first | .version // "Not found"' "$SBOM_JSON")
echo "| Python 3 | $PYTHON_VER | deb |"

# Perl
PERL_VER=$(jq -r '[.artifacts[] | select(.name == "perl-base") | select(.type == "deb-pkg")] | first | .version // "Not found"' "$SBOM_JSON")
echo "| Perl | $PERL_VER | deb |"
echo ""

# ===== Package Managers =====
echo "## Package Managers"
echo ""
echo "| Manager | Version | Source |"
echo "|---------|---------|--------|"

# npm
NPM_VER=$(jq -r '[.artifacts[] | select(.name == "npm") | select(.type == "npm-pkg")] | first | .version // "Not found"' "$SBOM_JSON")
echo "| npm | $NPM_VER | npm-pkg |"

# corepack
COREPACK_VER=$(jq -r '[.artifacts[] | select(.name == "corepack") | select(.type == "npm-pkg")] | first | .version // "Not found"' "$SBOM_JSON")
echo "| corepack | $COREPACK_VER | npm-pkg |"

# pnpm (via corepack — may or may not appear in SBOM)
PNPM_VER=$(jq -r '[.artifacts[] | select(.name == "pnpm")] | first | .version // "Not detected in image"' "$SBOM_JSON")
echo "| pnpm | $PNPM_VER | corepack |"

# yarn (via corepack)
YARN_VER=$(jq -r '[.artifacts[] | select(.name == "yarn")] | first | .version // "Not detected in image"' "$SBOM_JSON")
echo "| yarn | $YARN_VER | corepack |"

# apt/dpkg
echo "| apt/dpkg | (system) | Debian built-in |"
echo ""

# ===== CLI Tools =====
echo "## CLI Tools"
echo ""
echo "Notable CLI tools found in the image (from Syft deb package catalog):"
echo ""
echo "| Tool | Package | Version |"
echo "|------|---------|---------|"

# List of CLI tools to look for in deb packages
for tool in git gh curl wget openssh-client openssl gnupg ca-certificates \
            gcc g++ make autoconf automake subversion mercurial \
            tar gzip bzip2 xz-utils unzip procps findutils coreutils; do
    ROW=$(jq -r --arg name "$tool" \
        '[.artifacts[] | select(.name == $name and .type == "deb-pkg")] | first |
         if . then "| " + .name + " | " + .name + " | " + .version + " |" else empty end' \
        "$SBOM_JSON")
    if [ -n "$ROW" ]; then
        echo "$ROW"
    fi
done
echo ""

# ===== Vulnerability Summary =====
cat <<EOF
## Vulnerability Summary

Scanned by Trivy on $GENERATION_DATE.

| Severity | Count |
|----------|-------|
| CRITICAL | $VULN_CRITICAL |
| HIGH | $VULN_HIGH |
| MEDIUM | $VULN_MEDIUM |
| LOW | $VULN_LOW |
| **Total** | **$VULN_TOTAL** |

EOF

# Top critical/high CVEs
if [ "$VULN_CRITICAL" -gt 0 ] || [ "$VULN_HIGH" -gt 0 ]; then
    echo "### Critical and High CVEs"
    echo ""
    echo "| CVE ID | Severity | Package | Installed | Fixed |"
    echo "|--------|----------|---------|-----------|-------|"
    jq -r '
        [.Results[]?.Vulnerabilities[]? |
         select(.Severity == "CRITICAL" or .Severity == "HIGH")] |
        sort_by(.Severity) |
        .[:20][] |
        "| " + .VulnerabilityID + " | " + .Severity + " | " +
        .PkgName + " | " + .InstalledVersion + " | " +
        (.FixedVersion // "n/a") + " |"
    ' "$TRIVY_JSON"
    echo ""
fi

# ===== Runtime Environment =====
echo "## Runtime Environment"
echo ""
echo "Data below was collected by running \`runtime-inventory.sh\` inside the container."
echo ""

cat "$RUNTIME_MD"

# ===== Footer =====
cat <<EOF
---

**Generated**: $GENERATION_DATE
**Tools**: [Syft](https://github.com/anchore/syft) (SBOM), [Trivy](https://github.com/aquasecurity/trivy) (CVEs), runtime-inventory.sh
**Container Image**: \`ghcr.io/jedwards1230/openclaw:latest\`
EOF
